### ISSUE TITLE
Create sighting page doesn't work

### ISSUE THREAD

**Issue by kknaack-eiq** [eclecticiq/intelligence-center-app-splunk-ta#27]
the "create sighting page" doesn't work. clicking the "save" button doesn't do anything. if I check the console output of the browser is see the following error:
VM408:94 setup_page.js completeSetup called
VM408:96 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
at HTMLButtonElement.completeSetup (eval at <anonymous> (dashboard_1.1.js:1:1), <anonymous>:96:14)
at HTMLButtonElement.dispatch (common.js:489:60759)
at elemData.handle (common.js:489:57547)

**Comment by himynamesdave** [comment]
Can you please share more information about the browser you're using please?

**Comment by himynamesdave** [comment]
@aholzel confirmed

Working:

* Chrome version 107.0.5304.107

NOT working: 

* Firefox version 107.0 (64-bit)
* MS Edge version 107.0.1418.56
* Brave version 1.45.133 Chromium 107.0.5304.141

**Comment by raghavendra-sacumen** [comment]
Following Browser versions checked & Its [working]

- Brave version 1.45.133 
- Chromium 107.0.5304.141
- Firefox version 107.0 (64-bit)
- MS Edge version 107.0.1418.62

**Comment by himynamesdave** [comment]
@raghavendra-sacumen can you share some demo videos of this working? Ideally showing the console logs? I just want to check there's no errors being triggered on the requests in our tests. Thanks!

**Comment by raghavendra-sacumen** [comment]
@himynamesdave screenshots are attached as zip file [https://drive.google.com/drive/folders/17ku9-yXGScaiygVWuEakoufq05ljCHrU?usp=share_link].Will arrange to add demo as well.

**Comment by himynamesdave** [comment]
@raghavendra-sacumen ideally i'd like something that also includes the browser version shown please, hence a video is much better. Thanks!

**Comment by raghavendra-sacumen** [comment]
Hi @himynamesdave 
Please find the attached video links 
1. Brave Web browser https://drive.google.com/file/d/12EME_3m3s2LOul8kRiHY5tbnQcwJU9RK/view?usp=share_link
2. Firefox Web browser https://drive.google.com/file/d/1JdBiP26BxhdxSRXN2pQlkKgggyUdTX2Y/view?usp=share_link
3. MS Edge browser https://drive.google.com/file/d/1NXtSMQNsIy-_dLZVtx2FNxW_uP9zBPTO/view?usp=share_link
